[DEFAULT]

#Connexion a RabbitMQ sur la VM
transport_url = rabbit://openstack:openstack@192.168.212.136:5672

#IP de la machine physique pour que vnc fonctionne
my_ip = 192.168.212.1
state_path = /var/lib/nova
enabled_apis = osapi_compute,metadata

#activer le service reseau
use_true = True

#startegie d'authentification
auth_strategy = keystone

[api_database]
#Connexion a la BD nova_api sur la VM
connection = mysql+pymysql://nova:nova_pwd@192.168.212.1/nova_api

[database]
#Connexion a la BD nova sur la vm
connection = mysql+pymysql://nova:nova_pwd@192.168.212.1/nova

[keystone_authtoken]
#Connexion a keystone sur la vm
www_authenticate_uri = http://192.168.212.136:5000/
auth_url = http://192.168.212.136:5000/
memcached_servers = 192.168.212.136:11211
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = nova
password = nova

[glance]
api_servers = http://192.168.212.136:9292

[placement]
#nova a besoin du service placement 
os_region_name = RegionOne
auth_url = http://192.168.212.136:5000/v3
auth_type = password
project_domain_name = Default
user_domain_name = Default
Project_name = service
username = placement
password = placement
region_name = RegionOne
valid_interfaces = internal,public

[oslo_concurency]
lock_path = /var/lib/nova/tmp
